'use strict';
const express = require('express');
const router = express.Router();
const controller = require('./location.controller');
const { authenticate } = require('../../core/middleware/auth.middleware');
const { validate } = require('../../core/middleware/validate.middleware');
const { createLocationSchema, updateLocationSchema } = require('./location.schema');
const { requirePermissions } = require('../../core/middleware/rbac.middleware');
const { PERMISSIONS } = require('../../shared/constants/permissions');
router.use(authenticate);
router.get('/', requirePermissions([PERMISSIONS.HSE_VIEW_DASHBOARD]), controller.list);
router.get('/:id', requirePermissions([PERMISSIONS.HSE_VIEW_DASHBOARD]), controller.get);
router.post('/', requirePermissions([PERMISSIONS.HSE_MANAGE_PLANTS]), validate(createLocationSchema), controller.create);
router.put('/:id', requirePermissions([PERMISSIONS.HSE_MANAGE_PLANTS]), validate(updateLocationSchema), controller.update);
router.delete('/:id', requirePermissions([PERMISSIONS.HSE_MANAGE_PLANTS]), controller.remove);
module.exports = router;
